version: '3.8'
services:
  redis:
    ports:
      - '6379:6379'
    image: redis:latest
    volumes:
      - schachfish-cache:/data
    network_mode: host
  schachfish:
    ports:
      - '9100:9100'
    image: nicholasjb/schachfish:latest
    network_mode: host
volumes:
  schachfish-cache:
